### ISSUE TITLE
Configuration error preventing container startup

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet-geoapi#19]
The first, but might be more, configuration error preventing the app from starting up.

```
2022-12-15T08:36:18.079851121Z     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2022-12-15T08:36:18.079914921Z psycopg2.OperationalError: could not translate host name "[[REDACTED]].postgres.database.azure.com.postgres.database.azure.com" to address: Name or service not known
```

**Comment by JimCircadian** [comment]
Now getting 

```
2022-12-15T08:56:38.357249345Z Traceback (most recent call last):
2022-12-15T08:56:38.362799488Z   File "/tmp/8dade7890e47b4c/antenv/lib/python3.9/site-packages/pygeoapi/provider/postgresql.py", line 105, in __enter__
2022-12-15T08:56:38.363701495Z     self.conn = psycopg2.connect(**self.conn_dic)
2022-12-15T08:56:38.364195499Z   File "/tmp/8dade7890e47b4c/antenv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
2022-12-15T08:56:38.365056306Z     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2022-12-15T08:56:38.365076206Z psycopg2.OperationalError: FATAL:  database "psql-[[REDACTED]]-database" does not exist
```

Probably a mismatch

**Comment by JimCircadian** [comment]
Something awry has happened, as direct login to the resource dependency isn't working, so this is a problem in the [icenet-etl](https://github.com/icenet-ai/icenet-etl) provisioning

**Comment by JimCircadian** [comment]
Listing the databases, the database name is hardcoded to icenet. This can be changed herein

**Comment by JimCircadian** [comment]
Now getting some kind of nasty from the application itself:

```
2022-12-15T09:44:14.847569432Z Traceback (most recent call last):
2022-12-15T09:44:14.848312538Z   File "/tmp/8dade7e39531e98/run.py", line 34, in <module>
2022-12-15T09:44:14.848331838Z     sys.exit(cli(["serve"]))
2022-12-15T09:44:14.848540040Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
2022-12-15T09:44:14.856107497Z     return self.main(*args, **kwargs)
2022-12-15T09:44:14.856799803Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/click/core.py", line 782, in main
2022-12-15T09:44:14.857550408Z     rv = self.invoke(ctx)
2022-12-15T09:44:14.857786510Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
2022-12-15T09:44:14.858914619Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2022-12-15T09:44:14.865425568Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
2022-12-15T09:44:14.866097173Z     return ctx.invoke(self.callback, **ctx.params)
2022-12-15T09:44:14.866567077Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
2022-12-15T09:44:14.867439984Z     return callback(*args, **kwargs)
2022-12-15T09:44:14.867988788Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
2022-12-15T09:44:14.868752894Z     return f(get_current_context(), *args, **kwargs)
2022-12-15T09:44:14.869281098Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/pygeoapi/__init__.py", line 51, in serve
2022-12-15T09:44:14.875679947Z     from pygeoapi.flask_app import serve as serve_flask
2022-12-15T09:44:14.875941749Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/pygeoapi/flask_app.py", line 39, in <module>
2022-12-15T09:44:14.876423452Z     from pygeoapi.api import API
2022-12-15T09:44:14.876441152Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/pygeoapi/api.py", line 57, in <module>
2022-12-15T09:44:14.877059457Z     from pygeoapi.linked_data import (geojson2jsonld, jsonldify,
2022-12-15T09:44:14.877076357Z   File "/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/pygeoapi/linked_data.py", line 37, in <module>
2022-12-15T09:44:14.885123019Z     from shapely.geometry import asShape
2022-12-15T09:44:14.885148219Z ImportError: cannot import name 'asShape' from 'shapely.geometry' (/tmp/8dade7e39531e98/antenv/lib/python3.9/site-packages/shapely/geometry/__init__.py)
```

**Comment by JimCircadian** [comment]
This is likely down to Shapely 2.x being pulled in. The newer versions of pygeoapi have pinned <2, so have added that to the requirements. Should upgrade pygeoapi at some point...
